[[libdealii_trixi_paper2026]]
arch = "aarch64"
git-tree-sha1 = "9ba71900b5576bb54b49ae8caea336ca9df91ff1"
mpi = "mpich"
os = "macos"

    [[libdealii_trixi_paper2026.download]]
    sha256 = "b30d3459614aaf1528519e0f21f7a9bcafd32a27cfa73291b11f3248a053aba5"
    url = "https://github.com/trixi-framework/libdealii_trixi_paper2026_jll.jl/releases/download/libdealii_trixi_paper2026-v0.1.4+0/libdealii_trixi_paper2026.v0.1.4.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[libdealii_trixi_paper2026]]
arch = "aarch64"
git-tree-sha1 = "37a51c84d0b4016d92827bbc3bc5fc1bb64559dd"
mpi = "mpitrampoline"
os = "macos"

    [[libdealii_trixi_paper2026.download]]
    sha256 = "ba981e5d2960d61eb6533d3f38def0ec0185126ff2041bc30e72df58ecfaeeb3"
    url = "https://github.com/trixi-framework/libdealii_trixi_paper2026_jll.jl/releases/download/libdealii_trixi_paper2026-v0.1.4+0/libdealii_trixi_paper2026.v0.1.4.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[libdealii_trixi_paper2026]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "685cfc4781e46b6f168b835a8c683bcc8a24da1e"
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[libdealii_trixi_paper2026.download]]
    sha256 = "e979e5933d334791e9777251f45de5f0d50d627616cbbbe2a10d9008812be186"
    url = "https://github.com/trixi-framework/libdealii_trixi_paper2026_jll.jl/releases/download/libdealii_trixi_paper2026-v0.1.4+0/libdealii_trixi_paper2026.v0.1.4.aarch64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[libdealii_trixi_paper2026]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a34474f8a26503ac16ac6d7d30dba794b2d2fc3"
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[libdealii_trixi_paper2026.download]]
    sha256 = "c343e9bb0cf7b674f507fc785c5ce11423be6f198b67d898b88a2e721a7926ce"
    url = "https://github.com/trixi-framework/libdealii_trixi_paper2026_jll.jl/releases/download/libdealii_trixi_paper2026-v0.1.4+0/libdealii_trixi_paper2026.v0.1.4.aarch64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[libdealii_trixi_paper2026]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a823f7412dffa87ac2b67ab803265f7961f61f13"
libc = "musl"
mpi = "mpich"
os = "linux"

    [[libdealii_trixi_paper2026.download]]
    sha256 = "323c7536cf64660fb07599b5dcd08c7a6406ed7e378d1f4a4f8e1ebfcde178b2"
    url = "https://github.com/trixi-framework/libdealii_trixi_paper2026_jll.jl/releases/download/libdealii_trixi_paper2026-v0.1.4+0/libdealii_trixi_paper2026.v0.1.4.aarch64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[libdealii_trixi_paper2026]]
arch = "x86_64"
git-tree-sha1 = "200ef80d2d1d73c8bbba443ef22a2e77b9182f93"
mpi = "mpich"
os = "macos"

    [[libdealii_trixi_paper2026.download]]
    sha256 = "a13775c15dc78a4c19488918cae0fe14e6527ee616479f542d34fd5e8dc0bd52"
    url = "https://github.com/trixi-framework/libdealii_trixi_paper2026_jll.jl/releases/download/libdealii_trixi_paper2026-v0.1.4+0/libdealii_trixi_paper2026.v0.1.4.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[libdealii_trixi_paper2026]]
arch = "x86_64"
git-tree-sha1 = "5fb0fd023ffa3df88d66815cdacd007ef79c8f40"
mpi = "mpitrampoline"
os = "macos"

    [[libdealii_trixi_paper2026.download]]
    sha256 = "461e089703e5e65ab28dce7d3081d32af7e66e509b4f2cde0fd8bdf5b09755c1"
    url = "https://github.com/trixi-framework/libdealii_trixi_paper2026_jll.jl/releases/download/libdealii_trixi_paper2026-v0.1.4+0/libdealii_trixi_paper2026.v0.1.4.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[libdealii_trixi_paper2026]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95ed849bbbb0cd854771eccff6b0bdf1360072b3"
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[libdealii_trixi_paper2026.download]]
    sha256 = "2b74e9cb0f5ff62396ccd877dbd224e0a14337de2bbf8f0170adf7b8deb1eeda"
    url = "https://github.com/trixi-framework/libdealii_trixi_paper2026_jll.jl/releases/download/libdealii_trixi_paper2026-v0.1.4+0/libdealii_trixi_paper2026.v0.1.4.x86_64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[libdealii_trixi_paper2026]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e07260cd0d0442d93f6dce88ca7f94a701da1876"
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[libdealii_trixi_paper2026.download]]
    sha256 = "424fceb04259e7cac9be4cec1b70e07dfe20b20e48dec6379687e3e72f248ccb"
    url = "https://github.com/trixi-framework/libdealii_trixi_paper2026_jll.jl/releases/download/libdealii_trixi_paper2026-v0.1.4+0/libdealii_trixi_paper2026.v0.1.4.x86_64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[libdealii_trixi_paper2026]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfe5701ba03471bf6983ac97bad0667fdf183f37"
libc = "musl"
mpi = "mpich"
os = "linux"

    [[libdealii_trixi_paper2026.download]]
    sha256 = "4165ac94a8ca7d7ee7867734c0253858ac926d7d6bfb647b7d20fab590fb83ea"
    url = "https://github.com/trixi-framework/libdealii_trixi_paper2026_jll.jl/releases/download/libdealii_trixi_paper2026-v0.1.4+0/libdealii_trixi_paper2026.v0.1.4.x86_64-linux-musl-cxx11-mpi+mpich.tar.gz"
