# Autogenerated wrapper script for libdealii_trixi_paper2026_jll for x86_64-linux-musl-cxx11-mpi+mpich
export libdealii_trixi_paper2026

using MPIPreferences
using deal_II_jll
using MPICH_jll
JLLWrappers.@generate_wrapper_header("libdealii_trixi_paper2026")
JLLWrappers.@declare_library_product(libdealii_trixi_paper2026, "libdealii_trixi_paper2026.so")
function __init__()
    JLLWrappers.@generate_init_header(MPIPreferences, deal_II_jll, MPICH_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libdealii_trixi_paper2026,
        "lib/libdealii_trixi_paper2026.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
